### ISSUE TITLE
why not using an index file like libnss-cache?

### ISSUE THREAD

**Issue by t57root** [GoogleCloudPlatform/guest-oslogin#43]
At first I thought nss_cache_oslogin was forked from [libnss_cache](https://github.com/google/libnss-cache). But libnss-cache uses an index file for faster search while nss_cache_oslogin doesn't. 
Is there any reason to drop this mechanism in oslogin?

**Comment by hopkiw** [comment]
You're quite right, this code was originally a copied implementation of libnss_cache. I don't know why the index file wasn't included at that time; the code for it was copied over but never used. We later pruned that unused code.

Rather than restoring this however, we have a re-architecture planned for these components to enable more advanced forms of caching. You should look for this later this year.

**Comment by t57root** [comment]
> Rather than restoring this however, we have a re-architecture planned for these components to enable more advanced forms of caching. You should look for this later this year.

Cool! looking foward to the new cacheing mechanism!
