### ISSUE TITLE
How to handle groups assigned to users in a centralized way

### ISSUE THREAD

**Issue by marga-kinvolk** [GoogleCloudPlatform/guest-oslogin#45]
I need my oslogin-managed users to belong to groups like `docker` and `lxd`. I've been poring over all the available documentation, code, etc trying to figure out how to make this happen, but I was not able to find this information.

From looking at the code in this repo, it seems like oslogin is supposed to handle groups, but I couldn't find anything about how to set local groups. Getting the group information seems to fail for `google_oslogin_nss_cache`:

```
marga_kinvolk_io@instance-1 ~ $ sudo /usr/libexec/google_oslogin_nss_cache   
oslogin_cache_refresh[1360]: Refreshing passwd entry cache
oslogin_cache_refresh[1360]: Refreshing group entry cache
oslogin_cache_refresh[1360]: Failure getting groups, quitting
oslogin_cache_refresh[1360]: Produced empty group cache file, removing /etc/oslogin_group.cache.bak.
```

Running the same command with `strace` I see this:
```
sendto(5, "GET /computeMetadata/v1/oslogin/groups?pagesize=499 HTTP/1.1\r\nHost: metadata.google.internal\r\nAccept: */*\r\nMetadata-Flavor: Google\r\n\r\n", 134, MSG_NOSIGNAL, NULL, 0) = 134
1313  recvfrom(5, "HTTP/1.1 500 Internal Server Error\r\nMetadata-Flavor: Google\r\nDate: Fri, 18 Sep 2020 09:50:26 GMT\r\nContent-Type: text/html\r\nServer: Metadata Server for VM\r\nConnection: Close\r\nContent-Length: 14\r\nX-XSS-Protection: 0\r\nX-Frame-Options: SAMEORIGIN\r\n\r\ninternal error", 16384, 0, NULL, NULL) = 260
```

And sure enough, if I try that call myself I get the same error:
```
marga_kinvolk_io@instance-1 ~ $ curl "http://metadata.google.internal/computeMetadata/v1/oslogin/groups?pagesize=499&pagetoken=0" -H "Metadata-Flavor: Google"
internal error
```

This could be because my user requires some permission that's not available or something like that (it's not an "owner" user). But if that's the case, there's no documentation detailing which permissions are necessary. Also, other metadata calls work fine:

```
marga_kinvolk_io@instance-1 ~ $ curl "http://metadata.google.internal/computeMetadata/v1/oslogin/users?pagesize=1&pagetoken=0" -H "Metadata-Flavor: Google"
{"loginProfiles":[{"name":"103737192707657643592","posixAccounts":[{"primary":true,"username":"marga_kinvolk_io","uid":"1676322516","gid":"1676322516","homeDirectory":"/home/marga_kinvolk_io",....
```

I could find no documentation in the OS Login docs that mentioned the groups URL used by the `nss_cache` tool. I don't know if this used to work but no longer does or if it never worked.

In a separate attempt to get the groups to work, I tried modifying `/etc/security/group.conf` and adding some groups (taken from an old `guest-oslogin` entry):

```
marga_kinvolk_io@instance-1 ~ $ tail -1 /etc/security/group.conf 
sshd;*;*;Al0000-2400;adm,dip,docker,lxd,plugdev,video
```

But this also made no difference. My user doesn't belong to the necessary groups (not even after rebooting and logging in again).

So, would it be possible to please clarify how user groups are supposed to be managed when using oslogin? In particular, I want to make whatever necessary changes to ensure that any users created by oslogin belong to a bunch of groups, in the same way that this is possible by modifying `/etc/default/instance_configs.cfg` when not using oslogin.

Thanks!

**Comment by marga-kinvolk** [comment]
For the last point, I found that the issue was that my pam config didn't have `pam_group.so` enabled. After fixing that, my edits to `/etc/security/group.conf` work correctly.  Still interested in the rest of the question.

**Comment by illfelder** [comment]
Hi Marga, few things -

The groups endpoint that you are looking at is part of an Alpha feature that is currently whitelist only for Cloud Identity/G Suite organizations. The feature allows an organization administrator to set up centralized POSIX groups - users who are a member of the Google group would show up as a member of its associated POSIX group when logging into VMs within the organization. If you think this feature would be useful to you, let me know and we can get you whitelisted.

Separate from the groups metadata server endpoint, your question is specific to granting membership to the docker and lxd groups. For a little while we automatically added all OS Login users to these groups, but reverted that change because these groups enable privilege escalation routes to non-administrative users. Here's the relevant change: https://github.com/GoogleCloudPlatform/guest-oslogin/pull/29/files (if you build a package with this change reverted, users will appear in the specified groups as long as they exist on the VM).

As a final note, using standard group mod utilities, you should be able to add a user to the needed groups (though I understand manual configuration is a bad UX). We are also working on changes that will add sudo OS Login users to the groups you mentioned, but will not add users without admin permissions. I don't have a timeline I can provide on when that change will be merged and added to the Google provided images we publish, however.

**Comment by marga-kinvolk** [comment]
Hi Max,

Thanks a lot for your answer!

I'm preparing VM images for Flatcar Linux (a Container Optimized OS), and I want to solve this issue for everyone that will use the images, so having my organization whitelisted wouldn't help, but thanks for the offer. I guess the integration with POSIX groups would solve the problem that I'm trying to solve, but we'll need to wait until it's GA to integrate with it.

As a note, given that we provide VM images that work out-of-the-box, the solution of configuring user groups through the `/etc/default/instance_configs.cfg` file was pretty much what we needed, and it's a pity that this is not possible when using oslogin now :-/.

I understand why you removed docker and the other groups from the default, and it would indeed make sense to add them to the users that have sudo rights, as preventing a privilege escalation for them doesn't make sense.

For now, I've added my own `/etc/security/group.conf` that adds the docker group for the users of our images, as Flatcar without docker just doesn't make sense.  Once a version of oslogin supports adding the docker group to sudo users, we could use that instead (we wouldn't need to wait for Google provided images, as we're providing our images).

I guess you can close this now. Thanks again and have a great week!
