### ISSUE TITLE
Change the login shell of an oslogin user account in non-organizational GCP

### ISSUE THREAD

**Issue by kevinnls** [GoogleCloudPlatform/guest-oslogin#60]
I could not find any method of doing so. Is there any? I prefer zsh, but I can't change with `chsh` nor find a way to add metadata of some sorts in the GCP Console.

**Comment by kevinnls** [comment]
Okay. Just found this https://cloud.google.com/compute/docs/oslogin/manage-oslogin-in-an-org#modify-users. But is there any method for individual non-premium users? 

If not, will it be allowed in the future?

**Comment by illfelder** [comment]
There is no current method to update POSIX information for non-Workspace accounts. Any Cloud Identity customer can use the Cloud Directory API to update POSIX information - this includes free tier Cloud Identity users. The current limitations exist to prevent abuse by users who should not have administrative access to a project or organization, but we are looking into ways to support more rich functionality for non-Cloud Identity users.

Currently, the shell is not configured on POSIX accounts automatically generated by the OS Login API. This leaves the POSIX account information system agnostic (since not all shells are supported in all distros). Here is the line that determines the default shell used when the OS Login user does not have the property set: https://github.com/GoogleCloudPlatform/guest-oslogin/blob/master/src/include/compat.h#L68

**Comment by kevinnls** [comment]
thank you!
